apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbWw0ZFhodmJEcG5hSEJmUld0WGREaG9WVkk0WWxaMU9WVm5ablpaTUZFeU9ISmtlR1ZSTmtGWk5HTjRXbTlRIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
